services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE:    ${DB_NAME}
      MYSQL_USER:        ${DB_USER}
      MYSQL_PASSWORD:    ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_HOST:     ${DB_HOST}
      DB_USER:     ${DB_USER}
      DB_PASS:     ${DB_PASS}
      DB_NAME:     ${DB_NAME}
      JWT_SECRET:  ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:

